### PR TITLE
Disable driver cache generation when EP context is enabled for NPU

### PR DESCRIPTION
**Pull request by jatinwadhwa921**
Disable driver cache generation when EP context is enabled for NPU

### CODE REVIEW

**Comment by ankitm3k** [comment]
LGTM

**Comment by preetha-intel** [comment]
LGTM

**Review by preetha-intel — APPROVED** [review]

**Review by preetha-intel — APPROVED** [review]

**Comment by jatinwadhwa921** [comment]
This feature can be only merged after ov 2024.4.0 is officially released

**Comment by preetha-intel** [comment]
@Wadhwa, ***@***.***> Raise a separate PR with adding a condition on ov version. It needs to be in by 13/9 release
________________________________

**Pull request merged**
