### PR TITLE
Tejal api doc changes

### PR DESCRIPTION
**Pull request by preetha-intel**
### Description
API changes for Doc

### CODE REVIEW

**Comment by sfatimar** [comment]
I only see comments change, @preetha-intel why can we not merge this? Please raise PR to new branch ovep-develop-lnl-1.4

**Comment by preetha-intel** [comment]
@TejalKhade28  Can you update to the comments we reviewed the other day. A bit more detailed

**Comment by TejalKhade28** [comment]
> @TejalKhade28 Can you update to the comments we reviewed the other day. A bit more detailed

comments updated

**Comment by preetha-intel** [comment]
@TejalKhade28  The changes looks good. Can you fix the lint issues. Thanks

**Comment by TejalKhade28** [comment]
Lint issues fixed

**Comment by sfatimar** [comment]
Why are you guys merging https://github.com/intel/onnxruntime/pull/469 in ovep-develop-lnl-1.2 branch ?

**Pull request merged**
