### PR TITLE
Throw useful Exceptions from OVEP

### PR DESCRIPTION
**Pull request by sspintel**
This fixes the problems of:

- ORT throwing Unknown Exception instead of the correct order of cascading exceptions as expected
- Standardise exception handling using ORT_THROW instead of std::throw

### CODE REVIEW

**Comment by preetha-intel** [comment]
LGTM

Kindly resolve Lint failure

**Comment by preetha-intel** [comment]
LGTM 

Kindly resolve lint failures

**Comment by sspintel** [comment]
Fixed Lint issues

**Comment by sspintel** [comment]
Merging as the remaining lint issue is not in the scope of the PR and the rest of the issues are solved.

**Pull request merged**
