### PR TITLE
Refactor tensor initialization check for external weights and fixed lint issues

### PR DESCRIPTION
**Pull request by jatinwadhwa921**
Refactor tensor initialization check for external weights and fixed lint issues

### CODE REVIEW

**Comment by preetha-intel** [comment]
Kindly fix lint issues

**Comment by jatinwadhwa921** [comment]
> Kindly fix lint issues

Done

**Comment by preetha-intel** [comment]
@jatinwadhwa921  There is this windowsCI failure. Is it from this PR ?

**Comment by preetha-intel** [comment]
The windows CI failure is common on this branch. Needs to be handled seperately. Merging this PR.

**Pull request merged**
