### PR TITLE
Enable OpenCL Throttling for GPU Device

### PR DESCRIPTION
**Pull request by MaajidKhan**
**Description**: 
Enable GPU Throttling as a runtime option.

**Motivation and Context**
-  Implement GPU Throttling feature. Added GPU Throttling feature for iGPU's.
    when user enables it as a runtime option, it helps in reducing overall CPU usage of the application
-  Added changes to exercise this option using onnxruntime_perf_test application.

**Note:**
The changes have been verified by both c++ API and Python API.

**For C++ API:** Used onnxruntime_perf_test to verify it.
**Command:**
./onnxruntime_perf_test -r 100 -c 1 -v -e openvino -i "device_type|GPU_FP16 enable_gpu_throttling|true" /home/intel/maajid/project_files/data_models_onnx_and_tests/resnet50v1/resnet50-v1-7.onnx

**For Python API:** 
sess = rt.InferenceSession(str(sys.argv[1]), providers=['OpenVINOExecutionProvider'], provider_options=[{'device_type' : sys.argv[4]}, {'enable_gpu_throttling' : 'true'}])

**Some Testing results with Resnet50 Model (verified and working):**
Refer the comments section here:
https://jira.devtools.intel.com/browse/HAFP-1803

### CODE REVIEW

**Comment by smkarlap** [comment]
Though we commonly refer to it as GPU throttling, it is not exactly the GPU that is throttled, but the CPU. So calling it GPU throttling might be misleading as users would believe the GPU's are being slowed down. We need to find a more accurate name for the option.

**Comment by MaajidKhan** [comment]
> Though we commonly refer to it as GPU throttling, it is not exactly the GPU that is throttled, but the CPU. So calling it GPU throttling might be misleading as users would believe the GPU's are being slowed down. We need to find a more accurate name for the option.

I see. some other names I can think of are:
1.enable_cpu_throttling
2.reduce_cpu_throttling
3.enable_throttling   (This could be a good generic naming as everyone knows that throttling is specific to CPU)

Let me know, if any of the above names sounds good.
@smkarlap @sfatimar

**Comment by MaajidKhan** [comment]
Hey guys, let me know if we can merge this. LGTM.

**Comment by smkarlap** [comment]
LGTM

**Pull request merged**
