### PR TITLE
Reducing scope of ov::Model only between read_model and compile_model

### PR DESCRIPTION
**Pull request by javier-intel**
### Description
Reducing memory consumption during model is partitioned or ep_context is disabled

### Motivation and Context
Memory peak reduction for PSU models.

### CODE REVIEW

**Comment by sfatimar** [comment]
@javier-intel @MayureshV1 I re triggered the Internal CI and it failed again

**Comment by sfatimar** [comment]
You need to look at the fix again.

**Comment by javier-intel** [comment]
Hi Sahar, I have that change in the repo but don't remember what required it. That's why the build was succeeding locally. I'll add it to the PR.

**Comment by javier-intel** [comment]
@sfatimar I just added the const and also some lint issue I found.

**Comment by sfatimar** [comment]
It is failed again

**Comment by javier-intel** [comment]
Really sorry about that. The change to the .cc file didn't make it. I've pushed another update and hopefully it's all fixed now.

**Comment by sfatimar** [comment]
please make sure this is aligned with the base branch

**Comment by javier-intel** [comment]
I'm cancelling this PR in favor of https://github.com/intel/onnxruntime/pull/513 that also includes these changes.

**Pull request closed without merging**
