### PR TITLE
update: Upgraded to OpenVINO v2024.5

### PR DESCRIPTION
**Pull request by ankitm3k**
### Description
ORT EP Compatible to OpenVINO Toolkit v2024.5

### Motivation and Context
ORT EP must maintain synergy with OpenVINO Toolkit v2024.5

### CODE REVIEW

**Comment by sfatimar** [comment]
Need Unit Test C++ /Python Test C++ Report to Merge this PR

**Comment by sfatimar** [comment]
No change to support INT4 ?

**Comment by sfatimar** [comment]
DeQuantize Linear Node is not added

**Comment by ankitm3k** [comment]
> No change to support INT4 ?

This PR is meant for OV upgrade only, there will be a separate PR for this request.

**Comment by ankitm3k** [comment]
> DeQuantize Linear Node is not added

This PR is meant for OV upgrade only, ai.onnx.DequantizeLinear op is already supported since OV 2021.4 for all plugins.

` no_dimension_supported_.push_back({"DequantizeLinear", V_2021_4, {"All"}});`

**Comment by sfatimar** [comment]
LGTM

**Pull request merged**
